# Generated by Django 2.2.6 on 2019-10-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('campesinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emparejamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razones', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('favorabilidad', models.FloatField()),
                ('campesino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campesinos.Campesino')),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
    ]
