# Generated by Django 2.2.6 on 2019-10-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='minorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
    ]
