# Generated by Django 2.2.6 on 2019-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_oferta_minorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_entrega',
            field=models.DateTimeField(verbose_name='creation_date'),
        ),
    ]
