# Generated by Django 2.2.6 on 2019-10-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(max_length=250)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(verbose_name='creation_date')),
            ],
        ),
    ]
