# Generated by Django 2.2.6 on 2019-10-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
        ('productos', '0002_producto_campesino'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
    ]
